### ISSUE TITLE
如何在Data中添加自定义字段

### ISSUE THREAD

**Issue by zoyaforever** [xiaoyao9184/hj-t212-parser#12]
Data data = new Data();

        data.setQn("todo");
        data.setSt("31");
        data.setCn("1101");
        data.setPw("123456");

        CpData cpData = new CpData();
        cpData.setPolId("a34005");
        
        data.setCp(cpData);

请问如何在data或者cpData中添加自定义字段？
比如“reset = 1"这样的命令？

**Comment by xiaoyao9184** [comment]
@zoyaforever 你的使用方式已经超出HJ-T212协议的扩展范围，不过仍可以实现；
使用Map对象代替Data和CpData，相应的，对扩展字段的验证也不会受到支持。
你可以参照单元测试，对Map类型的数据进行序列化与反序列化：

https://github.com/xiaoyao9184/hj-t212-parser/blob/bc3bcdd10f2d12dfec965f2b403c85f5b1617418/hj-t212-parser/src/test/java/com/xy/format/hbt212/core/T212MapperTest.java#L39-L66

https://github.com/xiaoyao9184/hj-t212-parser/blob/bc3bcdd10f2d12dfec965f2b403c85f5b1617418/hj-t212-parser/src/test/java/com/xy/format/hbt212/core/T212MapperTest.java#L106-L140

**Comment by zoyaforever** [comment]
@xiaoyao9184  好的，谢谢
