### ISSUE TITLE
引入后需要大量依赖？

### ISSUE THREAD

**Issue by xxjkdtx** [xiaoyao9184/hj-t212-parser#16]
用maven方式从jitpack引入本项目的jar
尝试
`T212Mapper t212Mapper = new T212Mapper();`
执行，报错，需要validation。
照着你的测试类里的依赖一个个加进去，
Hibernate Validator--->需要el--->添加el--->还需要配置validation.xml
为什么测试里的依赖会影响正常使用？
您这个需要哪些依赖可以写在README里吗？

**Comment by jacktang** [comment]
@xxjkdtx 和楼上遇到同样的问题，我准备剥离或者自己写一个parser

**Comment by lichuangCN** [comment]
> @xxjkdtx 和楼上遇到同样的问题，我准备剥离或者自己写一个parser

老兄能提供一个解决方案不，感觉有点迷
