### ISSUE TITLE
MN字段校验问题

### ISSUE THREAD

**Issue by liyang2012** [xiaoyao9184/hj-t212-parser#19]
当MN超过14位，Flag=4时，校验不通过

![1606121543243](https://user-images.githubusercontent.com/3076937/99943483-55150d80-2dac-11eb-9400-d3dd60855bdd.jpg)

**Comment by xiaoyao9184** [comment]
是的，这里是有问题
MN 14位是2005年的标准，2017年的标准是24位，丢失了根据版本校验特性；
Flag在2017版中只定义到了后3位，即最大 0000 0111 = 7，允许扩展，故不应进行校验
