### ISSUE TITLE
compile errer

### ISSUE THREAD

**Issue by fatalfeel** [xiaoyao9184/hj-t212-parser#3]
public static void create_format_exception(Set<? extends ConstraintViolation> constraintViolationSet, Object result) throws T212FormatException
    {
        Map<String, String> typePropertys = constraintViolationSet
                                            .stream()
                                            .collect(Collectors.groupingBy
                                             (
                                                ConstraintViolation::getMessage,
                                                new Collector<ConstraintViolation,StringJoiner,String>()
                                                {
                                                    @Override
                                                    public Supplier<StringJoiner> supplier()
                                                    {
                                                        return () -> new StringJoiner(",", "", "");
                                                    }

                                                    @Override
                                                    public BiConsumer<StringJoiner, ConstraintViolation> accumulator()
                                                    {
                                                        return (s,cv) -> s.add("'" + cv.getPropertyPath() + "'");
                                                    }

                                                    @Override
                                                    public BinaryOperator<StringJoiner> combiner()
                                                    {
                                                        return StringJoiner::merge;
                                                    }

                                                    @Override
                                                    public Function<StringJoiner, String> finisher()
                                                    {
                                                        return StringJoiner::toString;
                                                    }

                                                    @Override
                                                    public Set<Characteristics> characteristics()
                                                    {
                                                        return Collections.emptySet();
                                                    }
                                                }
                                             ));

        String msg = typePropertys.entrySet()
                    .stream()
                    .map(kv -> "\t"
                    +
                    kv.getKey()
                    +
                    " -> "
                    +
                    kv.getValue()).collect(Collectors.joining("\n"));

        throw new T212FormatException("Validate error\n" + msg).withResult(result);
    }

    public static void create_format_exception2(Set<? extends ConstraintViolation> constraintViolationSet) throws T212FormatException {
        Map<String, List<ConstraintViolation>> typeCVs = constraintViolationSet
                .stream()
                .collect
                (
                    Collectors.groupingBy(ConstraintViolation::getMessage, Collectors.toList())
                );

        Map<String, String> typePropertys = typeCVs.entrySet()
                .stream()
                .map(kv->
                {
                    String pps = kv.getValue()
                                    .stream()
                                    .map(cv -> "'" + cv.getPropertyPath() + "'")
                                    .collect(Collectors.joining(","));
                    return new AbstractMap.SimpleEntry<>(kv.getKey(),pps);
                }).collect(Collectors.toMap(AbstractMap.SimpleEntry::getKey, AbstractMap.SimpleEntry::getValue));

        String msg = typePropertys.entrySet()
                                    .stream()
                                    .map(kv -> "\t"
                                    +
                                    kv.getKey()
                                    +
                                    " -> "
                                    +
                                    kv.getValue()).collect(Collectors.joining("\n"));

        throw new T212FormatException("Validate error\n" + msg);
    }

//////////////////////

C:\alpha_project\hjt212_2017\hj-t212-parser-master\hj-t212-parser\src\main\java\com\xy\format\hbt212\core\validator\clazz\FieldValidator.java
Error:(60, 45) java: no suitable method found for collect(java.util.stream.Collector<javax.validation.ConstraintViolation,capture#1 of ?,java.util.Map<java.lang.String,java.lang.String>>)
    method java.util.stream.Stream.<R>collect(java.util.function.Supplier<R>,java.util.function.BiConsumer<R,? super capture#2 of ? extends javax.validation.ConstraintViolation>,java.util.function.BiConsumer<R,R>) is not applicable
      (cannot infer type-variable(s) R
        (actual and formal argument lists differ in length))
    method java.util.stream.Stream.<R,A>collect(java.util.stream.Collector<? super capture#2 of ? extends javax.validation.ConstraintViolation,A,R>) is not applicable
      (cannot infer type-variable(s) R,A,capture#3 of ?,T,K,A,D
        (argument mismatch; java.util.stream.Collector<capture#2 of ? extends javax.validation.ConstraintViolation,capture#4 of ?,java.util.Map<java.lang.Object,java.lang.String>> cannot be converted to java.util.stream.Collector<? super capture#2 of ? extends javax.validation.ConstraintViolation,capture#4 of ?,java.util.Map<java.lang.Object,java.lang.String>>))
Error:(115, 42) java: incompatible types: cannot infer type-variable(s) T,K,A,D,capture#5 of ?,T
    (argument mismatch; invalid method reference
      method getMessage in interface javax.validation.ConstraintViolation<T> cannot be applied to given types
        required: no arguments
        found: java.lang.Object
        reason: actual and formal argument lists differ in length)
Error:(115, 43) java: invalid method reference
  non-static method getMessage() cannot be referenced from a static context

**Comment by xiaoyao9184** [comment]
@fatalfeel Sorry for late reply, 
I can't restore this compilation error on my PC (oracle jdk1.8.0_144).
But i think this is a bug of javac, see this https://stackoverflow.com/questions/37368060/why-this-code-compiles-with-jdk8u45-and-above-but-not-with-jdk8u25
