### ISSUE TITLE
format of DataTime in CpData.java: yyyyMMddHHmmss

### ISSUE THREAD

**Issue by zoyaforever** [xiaoyao9184/hj-t212-parser#5]
CpData.java
![image](https://user-images.githubusercontent.com/3738335/50267115-101a2b00-0461-11e9-8bae-62349054b593.png)

但提供的测试代码中：
`String h212 = "##0139ST=32;CN=2011;PW=123456;MN=LD130133000015;CP=&&DataTime=20160824003817000;B01-Rtd=36.91;011-Rtd=231.0,011-Flag=N;060-Rtd=1.803,060-Flag=N&&4980\r\n";
`
DataTime的format是yyyyMMddHHmmssSSS，两者不一致，所以直接运行readme提供的测试代码是会出错的？

**Comment by xiaoyao9184** [comment]
@zoyaforever 是的，以协议规范为准，某些格式错误（例如：yyyyMMddHHmmssSSS）虽不会影响解析，但会在开启校验特性下抛出异常，见下：
https://github.com/xiaoyao9184/hj-t212-parser/blob/df2ba7d7d7cab8fa2770943be61bb51922233fa6/hj-t212-parser/src/main/java/com/xy/format/hbt212/core/feature/VerifyFeature.java#L36

由于协议规范本身存在冲突问题，未见有完全符合协议的数据包，
根据经验，通常需要在抛出 `T212FormatException ` 异常时，
检查 `T212FormatException ` 方法 `getResult` 是否解析出兼容数据 `Data` 

https://github.com/xiaoyao9184/hj-t212-parser/blob/df2ba7d7d7cab8fa2770943be61bb51922233fa6/hj-t212-parser/src/main/java/com/xy/format/hbt212/exception/T212FormatException.java#L59

https://github.com/xiaoyao9184/hj-t212-parser/blob/df2ba7d7d7cab8fa2770943be61bb51922233fa6/hj-t212-parser/src/main/java/com/xy/format/hbt212/model/Data.java#L20

**Comment by zoyaforever** [comment]
好的，明白了。谢谢
