### ISSUE TITLE
SegmentParser中的92行buffer size 过小

### ISSUE THREAD

**Issue by zoyaforever** [xiaoyao9184/hj-t212-parser#7]
`

        CharBuffer buffer = CharBuffer.allocate(10);

        //之后的Token
        int len = ReaderStream.of(reader)
`

如果将allocate的size改成20，就可以正常解析了。

原因可能是对于key“a01001-Rtd”来说，光key的大小就占了10个字节了。

使用的测试字符串：
`
String h212 ="##0318QN=20190118162801464;ST=31;CN=2011;PW=123456;MN=ente12345;flag=4;CP=&&DataTime=20190118162800;a01001-Rtd=0.0,a01001-Flag=N;a01002-Rtd=30.0,a01002-Flag=N;a01006-Rtd=99.710,a01006-Flag=N;a01007-Rtd=0.0,a01007-Flag=N;a01008-Rtd=0.0,a01008-Flag=N;LA-Rtd=0.0,LA-Flag=N;a34002-Rtd=99.300,a34002-Flag=N;GPS-Rtd=0,GPS-Flag=N&&8581\r\n";
`

**Comment by xiaoyao9184** [comment]
已在 https://github.com/xiaoyao9184/hj-t212-parser/commit/aa9b345b734e3ac21cb945ce272816c96dfeb63e 支持
